"""add workout logs and routines

Revision ID: 299b0f051d9c
Revises: 4c6b43750c28
Create Date: 2026-04-19 18:58:08.140090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299b0f051d9c'
down_revision = '4c6b43750c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_logs', sa.Column('is_public', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_logs', 'is_public')
    # ### end Alembic commands ###
