"""add gif_url to seeded_workout_exercises

Revision ID: 4c6b43750c28
Revises: f122aee47664
Create Date: 2026-04-19 18:38:56.208999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6b43750c28'
down_revision = 'f122aee47664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeded_workout_exercises', sa.Column('gif_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeded_workout_exercises', 'gif_url')
    # ### end Alembic commands ###
