"""add target fields to workout_log_exercises

Revision ID: 786e836f0009
Revises: b1e97991b4d7
Create Date: 2026-04-30 00:18:35.416466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786e836f0009'
down_revision = 'b1e97991b4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log_exercises', sa.Column('target_sets', sa.Integer(), nullable=True))
    op.add_column('workout_log_exercises', sa.Column('target_reps_min', sa.Integer(), nullable=True))
    op.add_column('workout_log_exercises', sa.Column('target_reps_max', sa.Integer(), nullable=True))
    op.add_column('workout_log_exercises', sa.Column('target_weight_lbs', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_log_exercises', 'target_weight_lbs')
    op.drop_column('workout_log_exercises', 'target_reps_max')
    op.drop_column('workout_log_exercises', 'target_reps_min')
    op.drop_column('workout_log_exercises', 'target_sets')
    # ### end Alembic commands ###
