"""Initial tables: users, user_profiles, follows, workouts, exercises

Revision ID: 81f60f7fa86a
Revises: 
Create Date: 2026-03-25 02:10:09.280915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '81f60f7fa86a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_following_id'), table_name='following')
    op.drop_table('following')
    op.add_column('user_profiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('gym_name', sa.String(length=100), nullable=False))
    op.add_column('user_profiles', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('user_profiles', sa.Column('gym_level', sa.String(length=20), nullable=True))
    op.add_column('user_profiles', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('followers_count', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('following_count', sa.Integer(), nullable=False))
    op.add_column('user_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_unique_constraint(None, 'user_profiles', ['user_id'])
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_column('user_profiles', 'updated_at')
    op.drop_column('user_profiles', 'created_at')
    op.drop_column('user_profiles', 'following_count')
    op.drop_column('user_profiles', 'followers_count')
    op.drop_column('user_profiles', 'avatar_url')
    op.drop_column('user_profiles', 'bio')
    op.drop_column('user_profiles', 'gym_level')
    op.drop_column('user_profiles', 'full_name')
    op.drop_column('user_profiles', 'gym_name')
    op.drop_column('user_profiles', 'user_id')
    op.create_table('following',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name=op.f('following_follower_id_fkey')),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], name=op.f('following_following_id_fkey')),
    sa.PrimaryKeyConstraint('id', 'follower_id', 'following_id', name=op.f('following_pkey'))
    )
    op.create_index(op.f('ix_following_id'), 'following', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('workout_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exercise_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gif_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rest_period_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('exercises_workout_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    # ### end Alembic commands ###
