"""add category and target to Routine Exercises

Revision ID: a41e5f570d31
Revises: da2a617a72c6
Create Date: 2026-04-19 20:14:02.499813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41e5f570d31'
down_revision = 'da2a617a72c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routine_exercises', sa.Column('category', sa.String(), nullable=True))
    op.add_column('routine_exercises', sa.Column('target', sa.String(), nullable=True))
    op.add_column('routine_exercises', sa.Column('equipment', sa.String(), nullable=True))
    op.add_column('workout_log_exercises', sa.Column('category', sa.String(), nullable=True))
    op.add_column('workout_log_exercises', sa.Column('equipment', sa.String(), nullable=True))
    op.drop_column('workout_log_exercises', 'body_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_log_exercises', sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('workout_log_exercises', 'equipment')
    op.drop_column('workout_log_exercises', 'category')
    op.drop_column('routine_exercises', 'equipment')
    op.drop_column('routine_exercises', 'target')
    op.drop_column('routine_exercises', 'category')
    # ### end Alembic commands ###
