"""add seeded workout exercises table

Revision ID: a8ca5b3741c9
Revises: 3285b6da6577
Create Date: 2026-04-19 14:27:25.085633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ca5b3741c9'
down_revision = '3285b6da6577'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeded_workout_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seeded_workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_library_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rest_period_seconds', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_library_id'], ['exercise_library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeded_workout_id'], ['seeded_workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeded_workout_exercises')
    # ### end Alembic commands ###
