"""Add fitness tracking fields

Revision ID: b1e97991b4d7
Revises: 290398c56c8a
Create Date: 2026-04-20 16:20:11.509623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e97991b4d7'
down_revision = '290398c56c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('user_profiles', sa.Column('last_workout', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('current_workout', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('total_workouts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('user_profiles', sa.Column('day_streak', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'day_streak')
    op.drop_column('user_profiles', 'total_workouts')
    op.drop_column('user_profiles', 'current_workout')
    op.drop_column('user_profiles', 'last_workout')
    op.drop_column('user_profiles', 'weight')
    # ### end Alembic commands ###
