"""add category and target to seeded_workout_exercises

Revision ID: da2a617a72c6
Revises: de6bc0e94c8a
Create Date: 2026-04-19 19:20:13.815659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2a617a72c6'
down_revision = 'de6bc0e94c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeded_workout_exercises', sa.Column('category', sa.String(), nullable=True))
    op.add_column('seeded_workout_exercises', sa.Column('target', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeded_workout_exercises', 'target')
    op.drop_column('seeded_workout_exercises', 'category')
    # ### end Alembic commands ###
