"""rename body_part to category in exercise_library

Revision ID: de6bc0e94c8a
Revises: 299b0f051d9c
Create Date: 2026-04-19 19:13:51.717357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6bc0e94c8a'
down_revision = '299b0f051d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('category', sa.String(), nullable=True))
    op.drop_index(op.f('ix_exercise_library_body_part'), table_name='exercise_library')
    op.create_index(op.f('ix_exercise_library_category'), 'exercise_library', ['category'], unique=False)
    op.drop_column('exercise_library', 'body_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_library', sa.Column('body_part', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_exercise_library_category'), table_name='exercise_library')
    op.create_index(op.f('ix_exercise_library_body_part'), 'exercise_library', ['body_part'], unique=False)
    op.drop_column('exercise_library', 'category')
    # ### end Alembic commands ###
