"""add cover_image_url to seeded_workouts

Revision ID: f122aee47664
Revises: a8ca5b3741c9
Create Date: 2026-04-19 17:54:58.338662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f122aee47664'
down_revision = 'a8ca5b3741c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeded_workouts', sa.Column('cover_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeded_workouts', 'cover_image_url')
    # ### end Alembic commands ###
